image:
  file: ops/docker/gitpod.Dockerfile
# Commands to start on workspace startup
tasks:
  - name: ssh setup
    command: |
      echo -ne "$DEV_MACHINE_PRIVATE_SSH_KEY" > /tmp/ssh_key
      chmod 600 /tmp/ssh_key
      sleep 5
      ssh -o StrictHostKeyChecking=false -i /tmp/ssh_key $DEV_MACHINE_USER@$DEV_MACHINE_HOSTNAME
  - name: tailscaled
    command: sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up \
        --login-server=$TAILSCALE_LOGIN_SERVER \
        --auth-key=$TAILSCALE_PREAUTHKEY \
        --hostname=gitpod-hocus
      sleep 3
      mkdir -p ops/resources
      echo "export GITPOD_IP=$(tailscale ip | head -n1)" > ops/resources/gitpod-ip.sh
      echo "export DEV_MACHINE_HOSTNAME=$DEV_MACHINE_HOSTNAME" >> ops/resources/gitpod-ip.sh
      export REPO_PRIVATE_KEY_BASE64=$(echo -ne "$HOCUS_REPO_PRIVATE_KEY" | base64 -w 0)
      echo "export HOCUS_REPO_PRIVATE_KEY=\"\$(echo -n $REPO_PRIVATE_KEY_BASE64 | base64 -d)\"" >> ops/resources/gitpod-ip.sh
      ops/bin/rsync.sh
  - name: Agent+CP dev-env setup
    init: yarn install && npm run dev-prebuild && git lfs pull && ops/bin/prepare.sh
    command: |
      ops/bin/up.sh
      ops/bin/temporal-up.sh
      npm run dev
  - name: Temporal codec server
    init: |
      yarn install
    command: |
      PORT=1337 npx ts-node -r tsconfig-paths/register entrypoints/codec-server.ts
  - name: Terminal
    init: sleep 0.01
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 4200
    onOpen: ignore
vscode:
  extensions:
    - Prisma.prisma
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - GitHub.copilot
    - firsttris.vscode-jest-runner
    - dcortes92.FreeMarker
    - AntonLilleby.xp-freemarker-formatter
    - emeraldwalk.RunOnSave
    - pomdtr.excalidraw-editor
    - bierner.markdown-mermaid
    - ms-azuretools.vscode-docker
