[default]
check-filename = true
extend-ignore-re = [
    # Test private keys
    "(?s)-----BEGIN OPENSSH PRIVATE KEY-----.*-----END OPENSSH PRIVATE KEY-----",
    # JWT
    "\"([a-zA-Z0-9_=]+)\\.([a-zA-Z0-9_=]+)\\.([a-zA-Z0-9_\\-\\+/=]*)\"",
    "\"fileBA\"",
    "\"fileBB\"",
]

[files]
extend-exclude = [
    ".clinic",
    "public/font-awesome/*",
    "public/fonts/*",
    "ops/docker/resources/keycloak-db-dump.sql",
    "app/agent/block-registry/oci-schema/typebox/typescript-to-typebox.ts",
    "app/agent/block-registry/test-data/*.Dockerfile",
    "app/agent/block-registry/test-data/resources",
]

[type.excalidraw]
extend-glob = ["*.excalidraw"]
extend-ignore-re = [
    "\"id\": \".*\"",
    "\"containerId\": \".*\"",
    "\"elementId\": \".*\"",
]
