import type { GitObject, Prisma, Project } from "@prisma/client";
import { VmTaskStatus } from "@prisma/client";
import type { Any } from "ts-toolbelt";
import { v4 as uuidv4 } from "uuid";
import { Token } from "~/token";
import { unwrap, waitForPromises } from "~/utils.shared";

import type { createAgentInjector } from "./agent-injector";
import type { VMTaskOutput } from "./agent-util.types";
import type { BuildfsService } from "./buildfs.service";
import { SOLO_AGENT_INSTANCE_ID } from "./constants";
import { PidValidator } from "./pid.validator";
import type { PrebuildService } from "./prebuild.service";
import { execSshCmd, randomString } from "./utils";

export const createActivities = async (
  injector: ReturnType<typeof createAgentInjector>,
  db: Prisma.NonTransactionClient,
) => {
  const agentConfig = injector.resolve(Token.Config).agent();

  const fetchRepository = async (gitRepositoryId: bigint): Promise<void> => {
    const instanceId = `fetchrepo-${uuidv4()}`;
    const firecrackerService = injector.resolve(Token.FirecrackerService)(instanceId);
    const gitService = injector.resolve(Token.GitService);
    const repo = await db.gitRepository.findUniqueOrThrow({
      where: { id: gitRepositoryId },
      include: {
        gitRepositoryFiles: { include: { agentInstance: true, file: true } },
        sshKeyPair: true,
      },
    });
    const repoFile = unwrap(
      repo.gitRepositoryFiles.find((f) => f.agentInstance.externalId === SOLO_AGENT_INSTANCE_ID),
    );
    await gitService.fetchRepository(
      firecrackerService,
      {
        pathOnHost: repoFile.file.path,
        maxSizeMiB: 100000,
      },
      {
        url: repo.url,
        credentials: {
          privateSshKey: repo.sshKeyPair.privateKey,
        },
      },
    );
  };

  const buildfs = async (args: {
    /**
     * Used to construct file paths. Autogenerated if not specified.
     * Useful mostly for debugging.
     */
    runId?: string;
    /**
     * Path to a drive with a Dockerfile.
     */
    inputDrivePath: string;
    outputDrive: {
      pathOnHost: string;
      maxSizeMiB: number;
    };
    buildfsEventId: bigint;
    db: Prisma.NonTransactionClient;
  }): Promise<{ buildSuccessful: boolean }> => {
    const runId = args.runId ?? uuidv4();
    const instanceId = `buildfs-${runId}`;
    const firecrackerService = injector.resolve(Token.FirecrackerService)(instanceId);
    const agentUtilService = injector.resolve(Token.AgentUtilService);
    const buildfsService = injector.resolve(Token.BuildfsService);

    agentUtilService.createExt4Image(
      args.outputDrive.pathOnHost,
      args.outputDrive.maxSizeMiB,
      true,
    );

    const buildfsEvent = await db.buildfsEvent.findUniqueOrThrow({
      where: { id: args.buildfsEventId },
    });

    const result = await firecrackerService.withVM(
      {
        ssh: {
          username: "root",
          password: "root",
        },
        kernelPath: agentConfig.defaultKernel,
        rootFsPath: agentConfig.buildfsRootFs,
        extraDrives: [
          { pathOnHost: args.outputDrive.pathOnHost, guestMountPath: buildfsService.outputDir },
          { pathOnHost: args.inputDrivePath, guestMountPath: buildfsService.inputDir },
        ],
      },
      async ({ ssh, sshConfig }) => {
        const workdir = "/tmp/workdir";
        const buildfsScriptPath = `${workdir}/bin/buildfs.sh`;
        await execSshCmd({ ssh }, ["rm", "-rf", workdir]);
        await execSshCmd({ ssh }, ["mkdir", "-p", workdir]);
        await ssh.putDirectory(agentConfig.hostBuildfsResourcesDir, workdir);
        await execSshCmd({ ssh }, ["chmod", "+x", buildfsScriptPath]);

        const taskResults = await agentUtilService.execVmTasks(sshConfig, db, [
          { vmTaskId: buildfsEvent.vmTaskId },
        ]);
        return taskResults[0];
      },
    );

    return { buildSuccessful: result.status === VmTaskStatus.VM_TASK_STATUS_SUCCESS };
  };

  /**
   * Copies the contents of `repositoryDrivePath` into `outputDrivePath`, and checks
   * out the given branch there.
   *
   * Returns an array of `ProjectConfig`s or `null`s corresponding to the
   * `projectConfigPaths` argument. If a hocus config file is not present in a directory,
   * `null` is returned.
   */
  const checkoutAndInspect = async (args: {
    gitRepositoryId: bigint;
    /**
     * The repository will be checked out to this branch.
     */
    targetBranch: string;
    /**
     * A new drive will be created at this path.
     */
    outputDrivePath: string;
    /**
     * Relative paths to directories where `hocus.yml` files are located.
     */
    projectConfigPaths: string[];
  }): Promise<Awaited<ReturnType<PrebuildService["checkoutAndInspect"]>>> => {
    const instanceId = `checkout-and-inspect-${randomString(8)}`;
    const fcService = injector.resolve(Token.FirecrackerService)(instanceId);
    const prebuildService = injector.resolve(Token.PrebuildService);
    const gitRepository = await db.gitRepository.findUniqueOrThrow({
      where: { id: args.gitRepositoryId },
      include: {
        gitRepositoryFiles: { include: { agentInstance: true, file: true } },
      },
    });
    const repoFile = unwrap(
      gitRepository.gitRepositoryFiles.find(
        (f) => f.agentInstance.externalId === SOLO_AGENT_INSTANCE_ID,
      ),
    );
    return await prebuildService.checkoutAndInspect({
      fcService,
      repositoryDrivePath: repoFile.file.path,
      targetBranch: args.targetBranch,
      outputDrivePath: args.outputDrivePath,
      projectConfigPaths: args.projectConfigPaths,
    });
  };

  /**
   * Returns the result for every task.
   *
   * Assumes that there is a `hocus` user with passwordless sudo on the
   * filesystem drive, sshd is configured to start running automatically after VM boot,
   * and the corresponding public key to the private key used to connect to the VM
   * (`agentConfig.prebuildSshPrivateKey`) is already present in the `hocus` user's authorized_keys.
   */
  const prebuild = async (args: {
    runId?: string;
    projectDrivePath: string;
    filesystemDrivePath: string;
    env?: { [key: string]: string };
    prebuildEventId: bigint;
  }): Promise<VMTaskOutput[]> => {
    const runId = args.runId ?? uuidv4();
    const instanceId = `prebuild-${runId}`;
    const firecrackerService = injector.resolve(Token.FirecrackerService)(instanceId);
    const agentUtilService = injector.resolve(Token.AgentUtilService);
    const prebuildService = injector.resolve(Token.PrebuildService);

    const prebuildEvent = await db.prebuildEvent.findUniqueOrThrow({
      where: { id: args.prebuildEventId },
      include: { tasks: { include: { vmTask: true } } },
    });
    const tasks = prebuildEvent.tasks;
    return await firecrackerService.withVM(
      {
        ssh: {
          username: "hocus",
          privateKey: agentConfig.prebuildSshPrivateKey,
        },
        kernelPath: agentConfig.defaultKernel,
        rootFsPath: args.filesystemDrivePath,
        extraDrives: [
          { pathOnHost: args.projectDrivePath, guestMountPath: prebuildService.devDir },
        ],
      },
      async ({ ssh, sshConfig }) => {
        await Promise.all(
          tasks.map(async (task) => {
            const script = agentUtilService.generateTaskScript(task.originalCommand);
            const paths = prebuildService.getPrebuildTaskPaths(task.idx);
            await execSshCmd({ ssh }, ["mkdir", "-p", prebuildService.prebuildScriptsDir]);
            await agentUtilService.writeFile(ssh, paths.scriptPath, script);
          }),
        );

        return await agentUtilService.execVmTasks(
          sshConfig,
          db,
          tasks.map((t) => ({ vmTaskId: t.vmTask.id, env: args.env })),
        );
      },
    );
  };

  type StartWorkspaceReturnValue = {
    firecrackerProcessPid: number;
    vmIp: string;
    vmInstanceId: string;
    ipBlockId: number;
    taskPids: number[];
  };

  const startWorkspace = async (args: {
    runId?: string;
    filesystemDrivePath: string;
    projectDrivePath: string;
    authorizedKeys: string[];
    tasks: string[];
  }): Promise<StartWorkspaceReturnValue> => {
    const runId = args.runId ?? uuidv4();
    const instanceId = `startvm-${runId}`;
    const firecrackerService = injector.resolve(Token.FirecrackerService)(instanceId);
    const agentUtilService = injector.resolve(Token.AgentUtilService);
    const sshGatewayService = injector.resolve(Token.SSHGatewayService);
    const devDir = "/home/hocus/dev";
    const repositoryDir = `${devDir}/project`;
    const scriptsDir = `${devDir}/.hocus/command`;

    return await firecrackerService.withVM(
      {
        ssh: {
          username: "hocus",
          privateKey: agentConfig.prebuildSshPrivateKey,
        },
        kernelPath: agentConfig.defaultKernel,
        rootFsPath: args.filesystemDrivePath,
        extraDrives: [{ pathOnHost: args.projectDrivePath, guestMountPath: devDir }],
        shouldPoweroff: false,
      },
      async ({ ssh, vmIp, firecrackerPid, ipBlockId }) => {
        const taskFn = async (task: string, taskIdx: number): Promise<number> => {
          const script = agentUtilService.generateTaskScript(task);
          const scriptPath = `${scriptsDir}/task-${taskIdx}.sh`;
          const logPath = `${scriptsDir}/task-${taskIdx}.log`;
          await execSshCmd({ ssh }, ["mkdir", "-p", scriptsDir]);
          await agentUtilService.writeFile(ssh, scriptPath, script);

          const result = await execSshCmd({ ssh, opts: { cwd: repositoryDir } }, [
            "bash",
            "-o",
            "pipefail",
            "-o",
            "errexit",
            "-c",
            `bash "${scriptPath}" > "${logPath}" 2>&1 & echo "$!"`,
          ]);
          return Number(PidValidator.Parse(result.stdout));
        };
        const authorizedKeys = args.authorizedKeys.map((key) => key.trim());
        await agentUtilService.writeFile(
          ssh,
          "/home/hocus/.ssh/authorized_keys",
          authorizedKeys.join("\n") + "\n",
        );
        const taskPids = await Promise.all(args.tasks.map(taskFn));
        await firecrackerService.changeVMNetworkVisibility(ipBlockId, "public");
        await sshGatewayService.addPublicKeysToAuthorizedKeys(authorizedKeys);
        return {
          firecrackerProcessPid: firecrackerPid,
          vmIp,
          taskPids,
          ipBlockId,
          vmInstanceId: instanceId,
        };
      },
    );
  };

  const stopWorkspace = async (args: { instanceId: string; ipBlockId: number }): Promise<void> => {
    const firecrackerService = injector.resolve(Token.FirecrackerService)(args.instanceId);
    await firecrackerService.shutdownVM();
    await firecrackerService.releaseVmResources(args.ipBlockId);
  };

  const getProjectsAndGitObjects = async (
    gitRepositoryId: bigint,
    gitObjectIds: bigint[],
  ): Promise<{ projects: Project[]; gitObjects: GitObject[] }> => {
    const projects = await db.project.findMany({
      where: { gitRepositoryId: gitRepositoryId },
    });
    const gitObjects = await db.gitObject.findMany({
      where: { id: { in: gitObjectIds } },
    });
    if (gitObjects.length !== gitObjectIds.length) {
      throw new Error("Some git objects were not found");
    }
    return { projects, gitObjects };
  };

  type GetOrCreateBuildfsEventsReturnType = Any.Compute<
    Awaited<ReturnType<BuildfsService["getOrCreateBuildfsEvent"]>>
  >[];
  const getOrCreateBuildfsEvents = async (
    args: {
      contextPath: string;
      dockerfilePath: string;
      cacheHash: string | null;
      fsFilePath: string;
    }[],
  ): Promise<GetOrCreateBuildfsEventsReturnType> => {
    const buildfsService = injector.resolve(Token.BuildfsService);
    const agentUtilService = injector.resolve(Token.AgentUtilService);
    const agentInstance = await db.$transaction((tdb) =>
      agentUtilService.getOrCreateSoloAgentInstance(tdb),
    );
    return await db.$transaction((tdb) =>
      waitForPromises(
        args.map((arg) =>
          buildfsService.getOrCreateBuildfsEvent(tdb, {
            ...arg,
            cacheHash: arg.cacheHash ?? `CACHE_HASH_NULL_${uuidv4()}`,
            agentInstanceId: agentInstance.id,
          }),
        ),
      ),
    );
  };

  return {
    fetchRepository,
    buildfs,
    checkoutAndInspect,
    prebuild,
    startWorkspace,
    stopWorkspace,
    getProjectsAndGitObjects,
    getOrCreateBuildfsEvents,
  };
};
