#!/bin/bash
### BEGIN INIT INFO
# Provides:          dnssetup
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Setups /etc/hosts
### END INIT INFO
echo "127.0.0.1       localhost" >> /etc/hosts
