/* eslint-disable */
/**
 * This file was automatically generated by typescript-to-typebox.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run make -j to regenerate this file.
 */

import { Type, Static } from "@sinclair/typebox";

export type HttpsOpencontainersOrgSchemaDescriptorAnnotations = Static<
  typeof HttpsOpencontainersOrgSchemaDescriptorAnnotations
>;
export const HttpsOpencontainersOrgSchemaDescriptorAnnotations = Type.Object(
  {},
  {
    additionalProperties: Type.String(),
  },
);

export type HttpsOpencontainersOrgSchemaImageDescriptorMediaType = Static<
  typeof HttpsOpencontainersOrgSchemaImageDescriptorMediaType
>;
export const HttpsOpencontainersOrgSchemaImageDescriptorMediaType = Type.String();

export type Urls = Static<typeof Urls>;
export const Urls = Type.Array(Type.String());

export type HttpsOpencontainersOrgSchemaImageDescriptorMediaType1 = Static<
  typeof HttpsOpencontainersOrgSchemaImageDescriptorMediaType1
>;
export const HttpsOpencontainersOrgSchemaImageDescriptorMediaType1 = Type.String();

export type HttpsOpencontainersOrgSchemaDescriptor = Static<
  typeof HttpsOpencontainersOrgSchemaDescriptor
>;
export const HttpsOpencontainersOrgSchemaDescriptor = Type.Object(
  {
    mediaType: HttpsOpencontainersOrgSchemaImageDescriptorMediaType,
    size: Type.Number(),
    digest: Type.String(),
    urls: Type.Optional(Urls),
    data: Type.Optional(Type.String()),
    artifactType: Type.Optional(HttpsOpencontainersOrgSchemaImageDescriptorMediaType1),
    annotations: Type.Optional(HttpsOpencontainersOrgSchemaDescriptorAnnotations),
  },
  {
    additionalProperties: Type.Unknown(),
  },
);
