/* eslint-disable */
/**
 * This file was automatically generated by typescript-to-typebox.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run make -j to regenerate this file.
 */

import { Type, Static } from "@sinclair/typebox";

export type DefsDescriptor = Static<typeof DefsDescriptor>;
export const DefsDescriptor = Type.Object(
  {},
  {
    additionalProperties: Type.Unknown(),
  },
);
