/* eslint-disable */
/**
 * This file was automatically generated by typescript-to-typebox.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run make -j to regenerate this file.
 */

import { Type, Static } from "@sinclair/typebox";

export type HttpsOpencontainersOrgSchemaImageIndexSchemaVersion = Static<
  typeof HttpsOpencontainersOrgSchemaImageIndexSchemaVersion
>;
export const HttpsOpencontainersOrgSchemaImageIndexSchemaVersion = Type.Number();

export type HttpsOpencontainersOrgSchemaImageDescriptorMediaType = Static<
  typeof HttpsOpencontainersOrgSchemaImageDescriptorMediaType
>;
export const HttpsOpencontainersOrgSchemaImageDescriptorMediaType = Type.String();

export type HttpsOpencontainersOrgSchemaImageDescriptorMediaType1 = Static<
  typeof HttpsOpencontainersOrgSchemaImageDescriptorMediaType1
>;
export const HttpsOpencontainersOrgSchemaImageDescriptorMediaType1 = Type.String();

export type Urls = Static<typeof Urls>;
export const Urls = Type.Array(Type.String());

export type HttpsOpencontainersOrgSchemaImagePlatformArchitecture = Static<
  typeof HttpsOpencontainersOrgSchemaImagePlatformArchitecture
>;
export const HttpsOpencontainersOrgSchemaImagePlatformArchitecture = Type.String();

export type HttpsOpencontainersOrgSchemaImagePlatformOs = Static<
  typeof HttpsOpencontainersOrgSchemaImagePlatformOs
>;
export const HttpsOpencontainersOrgSchemaImagePlatformOs = Type.String();

export type HttpsOpencontainersOrgSchemaImagePlatformOsVersion = Static<
  typeof HttpsOpencontainersOrgSchemaImagePlatformOsVersion
>;
export const HttpsOpencontainersOrgSchemaImagePlatformOsVersion = Type.String();

export type HttpsOpencontainersOrgSchemaImagePlatformOsFeatures = Static<
  typeof HttpsOpencontainersOrgSchemaImagePlatformOsFeatures
>;
export const HttpsOpencontainersOrgSchemaImagePlatformOsFeatures = Type.Array(Type.String());

export type HttpsOpencontainersOrgSchemaImageIndexAnnotations = Static<
  typeof HttpsOpencontainersOrgSchemaImageIndexAnnotations
>;
export const HttpsOpencontainersOrgSchemaImageIndexAnnotations = Type.Object(
  {},
  {
    additionalProperties: Type.String(),
  },
);

export type HttpsOpencontainersOrgSchemaImageDescriptorAnnotations = Static<
  typeof HttpsOpencontainersOrgSchemaImageDescriptorAnnotations
>;
export const HttpsOpencontainersOrgSchemaImageDescriptorAnnotations = Type.Object(
  {},
  {
    additionalProperties: Type.String(),
  },
);

export type HttpsOpencontainersOrgSchemaImagePlatform = Static<
  typeof HttpsOpencontainersOrgSchemaImagePlatform
>;
export const HttpsOpencontainersOrgSchemaImagePlatform = Type.Object(
  {
    architecture: HttpsOpencontainersOrgSchemaImagePlatformArchitecture,
    os: HttpsOpencontainersOrgSchemaImagePlatformOs,
    "os.version": Type.Optional(HttpsOpencontainersOrgSchemaImagePlatformOsVersion),
    "os.features": Type.Optional(HttpsOpencontainersOrgSchemaImagePlatformOsFeatures),
    variant: Type.Optional(Type.String()),
  },
  {
    additionalProperties: Type.Unknown(),
  },
);

export type HttpsOpencontainersOrgSchemaImageManifestDescriptor = Static<
  typeof HttpsOpencontainersOrgSchemaImageManifestDescriptor
>;
export const HttpsOpencontainersOrgSchemaImageManifestDescriptor = Type.Object(
  {
    mediaType: HttpsOpencontainersOrgSchemaImageDescriptorMediaType1,
    size: Type.Number(),
    digest: Type.String(),
    urls: Type.Optional(Urls),
    platform: Type.Optional(HttpsOpencontainersOrgSchemaImagePlatform),
    annotations: Type.Optional(HttpsOpencontainersOrgSchemaImageDescriptorAnnotations),
  },
  {
    additionalProperties: Type.Unknown(),
  },
);

export type HttpsOpencontainersOrgSchemaImageIndex = Static<
  typeof HttpsOpencontainersOrgSchemaImageIndex
>;
export const HttpsOpencontainersOrgSchemaImageIndex = Type.Object(
  {
    schemaVersion: HttpsOpencontainersOrgSchemaImageIndexSchemaVersion,
    mediaType: Type.Optional(HttpsOpencontainersOrgSchemaImageDescriptorMediaType),
    manifests: Type.Array(HttpsOpencontainersOrgSchemaImageManifestDescriptor),
    annotations: Type.Optional(HttpsOpencontainersOrgSchemaImageIndexAnnotations),
  },
  {
    additionalProperties: Type.Unknown(),
  },
);
