version: "3"
networks:
  hocus_dev_net:
    name: hocus_dev_net
services:
  agent:
    networks:
      - hocus_dev_net
    container_name: agent
    image: worker-dev
    restart: "no"
    privileged: true
    ports:
      - "${NO_EXPOSE_PORTS-8822:}22"
    volumes:
      - "${AGENT_REPO_DIR}:/app"
      - "${HOCUS_RESOURCES_DIR}:/srv/jailer"
      - /dev/kvm:/dev/kvm
    environment:
      - "HOCUS_DEV_GIT_NAME=${HOCUS_DEV_GIT_NAME}"
      - "HOCUS_DEV_GIT_EMAIL=${HOCUS_DEV_GIT_EMAIL}"
      - "DB_HOST=db"
      #- NODE_DEBUG=module
    entrypoint: /app/ops/bin/worker-in-hocus-entrypoint.sh
