version: "3"
networks:
  hocus_test_net:
volumes:
  agent-test-data:
services:
  db:
    image: "postgres:alpine"
    command: postgres -c 'max_connections=10000' -c 'shared_buffers=2GB' -c 'effective_cache_size=6GB' -c 'maintenance_work_mem=512MB' -c 'random_page_cost=1.1' -c 'effective_io_concurrency=200' -c 'work_mem=4MB' -c 'min_wal_size=2GB' -c 'max_wal_size=8GB' -c 'max_worker_processes=8' -c 'max_parallel_workers_per_gather=4' -c 'max_parallel_workers=8' -c 'max_parallel_maintenance_workers=4' -c 'fsync=off' -c 'full_page_writes=off' -c 'synchronous_commit=off' -c 'wal_level=minimal' -c 'max_wal_senders=0' -c 'log_error_verbosity=terse'
    restart: unless-stopped
    ports:
      - "${NO_EXPOSE_PORTS-5432:}5432"
    networks:
      - hocus_test_net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: rooms
      PGDATA: /pgtmpfs
    tmpfs:
      - /pgtmpfs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 10s
      retries: 30

  setup-vm-images:
    # We need to mount images and have access to the docker daemon
    # TODO: build images in kaniko and export tarballs using virt-make-fs
    privileged: true
    build:
      dockerfile: ops/docker/setup.Dockerfile
      context: ${REPO_DIR}
    restart: "no"
    command: |
      bash -o errexit -o nounset -o pipefail -o xtrace -c "
        mkdir -pv /agent_data/firecracker
        mkdir -pv /agent_data/resources
        ops/bin/buildfs.sh resources/docker/checkout-and-inspect.Dockerfile /agent_data/resources/checkout-and-inspect.ext4 resources/ 500
        ops/bin/buildfs.sh resources/docker/default-workspace.Dockerfile /agent_data/resources/default-workspace.ext4 resources/ 1500
        ops/bin/buildfs.sh resources/docker/buildfs.Dockerfile /agent_data/resources/buildfs.ext4 resources/ 1000
        ops/bin/buildfs.sh resources/docker/fetchrepo.Dockerfile /agent_data/resources/fetchrepo.ext4 resources 2500
        curl --retry-all-errors --connect-timeout 5 --retry 5 --retry-delay 0 --retry-max-time 40 https://github.com/hocus-dev/linux-kernel/releases/download/0.0.3/vmlinux -z /agent_data/resources/vmlinux-5.10-x86_64.bin -o /agent_data/resources/vmlinux-5.10-x86_64.bin --location
        ops/bin/dev/build-test-buildfs.sh /agent_data/resources
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent-test-data:/agent_data:rw

  agent:
    build:
      dockerfile: ops/docker/agent-tests.Dockerfile
      context: ${REPO_DIR}
    depends_on:
      db:
        condition: service_healthy
      setup-vm-images:
        condition: service_completed_successfully
    restart: "no"
    privileged: true
    ports:
      - "${NO_EXPOSE_PORTS-8822:}22"
    networks:
      - hocus_test_net
    volumes:
      - "agent-test-data:/srv/jailer"
      - /dev/kvm:/dev/kvm
    command: sleep infinity
