version: "3"
networks:
  hocus_dev_net:
    name: hocus_dev_net
services:
  gen:
    image: alpine:latest
    volumes:
      - ./:/data
    command: >
      sh -c '
        cd /data && \
        cp resources/keycloak-setup.sh db-init/keycloak-setup.sh && \
        sed -i -e "/-- SQL_DB_DUMP_GOES_HERE/r resources/keycloak-db-dump.sql" db-init/keycloak-setup.sh && \
        sed -i \
          "s/github_client_secret_goes_here/${GITHUB_APP_HOCUS_DEV_CLIENT_SECRET}/g" \
          db-init/keycloak-setup.sh && \
        sed -i \
          "s@hocus_callback_url_goes_here@http://localhost:3000/app/callback@g" \
          db-init/keycloak-setup.sh && \
        sed -i \
          "s@hocus_logout_redirect_url_goes_here@http://localhost:3000/@g" \
          db-init/keycloak-setup.sh
      '
  db:
    image: "postgres:alpine"
    networks:
      - hocus_dev_net
    command: postgres -c 'max_connections=10000' -c 'shared_buffers=2GB' -c 'effective_cache_size=6GB' -c 'maintenance_work_mem=512MB' -c 'random_page_cost=1.1' -c 'effective_io_concurrency=200' -c 'work_mem=4MB' -c 'min_wal_size=2GB' -c 'max_wal_size=8GB' -c 'max_worker_processes=8' -c 'max_parallel_workers_per_gather=4' -c 'max_parallel_workers=8' -c 'max_parallel_maintenance_workers=4' -c 'fsync=off' -c 'full_page_writes=off' -c 'synchronous_commit=off' -c 'wal_level=minimal' -c 'max_wal_senders=0' -c 'log_error_verbosity=terse'
    restart: unless-stopped
    ports:
      - 5432:5432
    depends_on:
      gen:
        condition: service_completed_successfully
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: rooms
      PGDATA: /pgtmpfs
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
    tmpfs:
      - /pgtmpfs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 10s
      retries: 30

  keycloak:
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hocus_dev_net
    command: "start"
    build:
      dockerfile: keycloak-dev.Dockerfile
    ports:
      - "4200:8080"
    restart: unless-stopped
